server:
  port: 8091
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        hbm2dd1:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  cloud:
    nacos:
      discovery:
        server-addr: 39.99.228.233:8848
    sentinel:
      transport:
        port: 9999 #和控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8080 # 指定控制台服务的地址
      filter:
        enabled: false
service-product: # 调用的提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

#rocketmq
rocketmq:
  name-server: 39.99.228.233:9876  #rocketMQ服务地址
  producer:
    group: shop-order #生产者组
